name: Deploy and Run Model on EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ubuntu@65.0.21.139  # The instance
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -i private_key -o StrictHostKeyChecking=no -r ./* $HOST:~/model_deployment/
        ssh -i private_key -o StrictHostKeyChecking=no $HOST << EOF
          cd ~/model_deployment
          
          # Set up and run the Flask app
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          
          # Run the app with sudo (required for port 80) and keep it running
          sudo nohup venv/bin/python app.py > app.log 2>&1 &
        EOF
        rm -f private_key